version: '3'
services:
  recipe_service:
    build:
      context: .
    image: ragnaruk/recipe_service:latest
    volumes:
      - ./data/:/recipe_service/data/
    ports:
      - 8080:8080
    command: ['python', './src/']